# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'narative_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(668, 721)
        font = QtGui.QFont()
        font.setFamily("Avenir")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("font: \"Avenir\";\n"
"background-color: rgb(35, 35, 35);\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 5, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Avenir")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font-weight: 800;\n"
"font: 24pt \"Avenir\";")
        self.label.setAlignment(Qt.Alignment.AlignCenter)
        self.label.setObjectName("label")
        self.checkBoxATrip = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxATrip.setGeometry(QtCore.QRect(20, 70, 61, 20))
        self.checkBoxATrip.setStyleSheet("")
        self.checkBoxATrip.setObjectName("checkBoxATrip")
        self.checkBoxBTrip = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxBTrip.setGeometry(QtCore.QRect(80, 70, 61, 20))
        self.checkBoxBTrip.setStyleSheet("")
        self.checkBoxBTrip.setObjectName("checkBoxBTrip")
        self.patientSelectionBox = QtWidgets.QComboBox(self.centralwidget)
        self.patientSelectionBox.setGeometry(QtCore.QRect(20, 100, 61, 41))
        self.patientSelectionBox.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.patientSelectionBox.setObjectName("patientSelectionBox")
        self.narativeLabel = QtWidgets.QLabel(self.centralwidget)
        self.narativeLabel.setGeometry(QtCore.QRect(40, 370, 551, 281))
        self.narativeLabel.setStyleSheet("font: 12pt \"Avenir\";\n"
"background-color: rgb(255, 255, 255);\n"
"padding: 5px;\n"
"border-radius: 7px;\n"
"color: rgb(0, 0, 0);")
        self.narativeLabel.setWordWrap(True)
        self.narativeLabel.setObjectName("narativeLabel")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 330, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Avenir")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font-weight: 800;\n"
"font: 24pt \"Avenir\";\n"
"background-color: none;")
        self.label_2.setAlignment(Qt.Alignment.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 320, 621, 351))
        self.label_3.setStyleSheet("background-color: rgb(128, 80, 77);\n"
"border-radius: 7px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.generateButton = QtWidgets.QPushButton(self.centralwidget)
        self.generateButton.setGeometry(QtCore.QRect(10, 160, 91, 31))
        self.generateButton.setStyleSheet("background-color: rgb(225, 222, 227);\n"
"border-radius: 12px;\n"
"font: 12pt \"Avenir\";\n"
"color: rgb(0, 0, 0);")
        self.generateButton.setObjectName("generateButton")
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(120, 160, 91, 31))
        self.clearButton.setStyleSheet("background-color: rgb(225, 222, 227);\n"
"border-radius: 12px;\n"
"font: 12pt \"Avenir\";\n"
"color: rgb(0, 0, 0);")
        self.clearButton.setObjectName("clearButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(246, 5, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Avenir")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font-weight: 800;\n"
"font: 24pt \"Avenir\";")
        self.label_4.setAlignment(Qt.Alignment.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.doctorTripBox = QtWidgets.QComboBox(self.centralwidget)
        self.doctorTripBox.setGeometry(QtCore.QRect(330, 50, 201, 41))
        self.doctorTripBox.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.doctorTripBox.setObjectName("doctorTripBox")
        self.doctorTripBox.addItem("")
        self.doctorTripBox.addItem("")
        self.doctorTripBox.addItem("")
        self.doctorTripBox.addItem("")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(240, 50, 91, 41))
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(240, 100, 101, 51))
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.doctorOfficeName = QtWidgets.QLineEdit(self.centralwidget)
        self.doctorOfficeName.setGeometry(QtCore.QRect(350, 110, 171, 31))
        self.doctorOfficeName.setStyleSheet("background-color:  none;\n"
"color: rgb(0, 0, 0);")
        self.doctorOfficeName.setObjectName("doctorOfficeName")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(240, 160, 101, 51))
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.doctorOfficeAddress = QtWidgets.QLineEdit(self.centralwidget)
        self.doctorOfficeAddress.setGeometry(QtCore.QRect(350, 170, 171, 31))
        self.doctorOfficeAddress.setStyleSheet("background-color:  none;\n"
"color: rgb(0, 0, 0);")
        self.doctorOfficeAddress.setObjectName("doctorOfficeAddress")
        self.patientSelectionBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.patientSelectionBox_2.setGeometry(QtCore.QRect(370, 220, 61, 41))
        self.patientSelectionBox_2.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.patientSelectionBox_2.setObjectName("patientSelectionBox_2")
        self.generateButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.generateButton_2.setGeometry(QtCore.QRect(300, 270, 91, 31))
        self.generateButton_2.setStyleSheet("background-color: rgb(225, 222, 227);\n"
"border-radius: 12px;\n"
"font: 12pt \"Avenir\";\n"
"color: rgb(0, 0, 0);")
        self.generateButton_2.setObjectName("generateButton_2")
        self.clearButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton_2.setGeometry(QtCore.QRect(410, 270, 91, 31))
        self.clearButton_2.setStyleSheet("background-color: rgb(225, 222, 227);\n"
"border-radius: 12px;\n"
"font: 12pt \"Avenir\";\n"
"color: rgb(0, 0, 0);")
        self.clearButton_2.setObjectName("clearButton_2")
        self.patientManageButton = QtWidgets.QPushButton(self.centralwidget)
        self.patientManageButton.setGeometry(QtCore.QRect(560, 5, 101, 41))
        self.patientManageButton.setStyleSheet("background-color: rgb(225, 222, 227);\n"
"border-radius: 12px;\n"
"font: 12pt \"Avenir\";\n"
"color: rgb(0, 0, 0);")
        self.patientManageButton.setObjectName("patientManageButton")
        self.label_3.raise_()
        self.label.raise_()
        self.checkBoxATrip.raise_()
        self.checkBoxBTrip.raise_()
        self.patientSelectionBox.raise_()
        self.narativeLabel.raise_()
        self.label_2.raise_()
        self.generateButton.raise_()
        self.clearButton.raise_()
        self.label_4.raise_()
        self.doctorTripBox.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.doctorOfficeName.raise_()
        self.label_7.raise_()
        self.doctorOfficeAddress.raise_()
        self.patientSelectionBox_2.raise_()
        self.generateButton_2.raise_()
        self.clearButton_2.raise_()
        self.patientManageButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 668, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Dialysis Trip"))
        self.checkBoxATrip.setText(_translate("MainWindow", "A Trip"))
        self.checkBoxBTrip.setText(_translate("MainWindow", "B Trip"))
        self.patientSelectionBox.setItemText(0, _translate("MainWindow", "GS"))
        self.patientSelectionBox.setItemText(1, _translate("MainWindow", "DP"))
        self.patientSelectionBox.setItemText(2, _translate("MainWindow", "SD"))
        self.patientSelectionBox.setItemText(3, _translate("MainWindow", "MT"))
        self.patientSelectionBox.setItemText(4, _translate("MainWindow", "AR"))
        self.patientSelectionBox.setItemText(5, _translate("MainWindow", "MP"))
        self.narativeLabel.setText(_translate("MainWindow", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sed luctus magna. Fusce porta, erat nec euismod pellentesque, mauris nunc egestas arcu, at euismod eros nulla vehicula lacus. In faucibus libero vel lacus facilisis, at dictum turpis fringilla. Nunc egestas feugiat bibendum. Phasellus ac malesuada lectus. Integer pharetra ac dui nec sagittis. Nulla tempor nunc non augue pretium, a sodales tortor euismod. Pellentesque molestie velit nulla, ultricies rutrum eros pulvinar vitae. Maecenas vulputate porta ante. Pellentesque vitae dolor viverra, suscipit dolor non, pellentesque magna. Aliquam condimentum, lacus vel venenatis lobortis, quam lacus vehicula lacus, quis finibus nibh nisi imperdiet lorem. Proin mollis nisl nec orci sodales sagittis. Vivamus in ligula sed purus feugiat sollicitudin. Integer eget suscipit purus, nec fermentum nunc. Cras id orci neque. Sed a metus eros.\n"
"\n"
"Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam tortor sapien, porttitor et nunc nec, vulputate dapibus massa. Mauris tincidunt condimentum tincidunt. Suspendisse efficitur in est at vulputate. Nam commodo ante sed rhoncus ultricies. Sed porta maximus fermentum. Sed quis consequat ex, nec elementum nisi."))
        self.label_2.setText(_translate("MainWindow", "Narative:"))
        self.generateButton.setText(_translate("MainWindow", "Generate"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.label_4.setText(_translate("MainWindow", "Doctor\'s Appointment Trip"))
        self.doctorTripBox.setItemText(0, _translate("MainWindow", "A trip from home to doctor"))
        self.doctorTripBox.setItemText(1, _translate("MainWindow", "A trip from dialysis to doctor"))
        self.doctorTripBox.setItemText(2, _translate("MainWindow", "B trip from doctor to home"))
        self.doctorTripBox.setItemText(3, _translate("MainWindow", "B trip from doctor to dialysis"))
        self.label_5.setText(_translate("MainWindow", "What kind of trip?"))
        self.label_6.setText(_translate("MainWindow", "What\'s the name of doctor\'s office?"))
        self.label_7.setText(_translate("MainWindow", "What\'s the address of doctor\'s office?"))
        self.patientSelectionBox_2.setItemText(0, _translate("MainWindow", "GS"))
        self.patientSelectionBox_2.setItemText(1, _translate("MainWindow", "DP"))
        self.patientSelectionBox_2.setItemText(2, _translate("MainWindow", "SD"))
        self.patientSelectionBox_2.setItemText(3, _translate("MainWindow", "MT"))
        self.patientSelectionBox_2.setItemText(4, _translate("MainWindow", "AR"))
        self.patientSelectionBox_2.setItemText(5, _translate("MainWindow", "MP"))
        self.generateButton_2.setText(_translate("MainWindow", "Generate"))
        self.clearButton_2.setText(_translate("MainWindow", "Clear"))
        self.patientManageButton.setText(_translate("MainWindow", "Manage Patients"))
