# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'patient_management_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(748, 599)
        MainWindow.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"color: rgb(255, 255, 255);\n"
"font: 13pt \"Avenir\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.patientView = QtWidgets.QTableView(self.centralwidget)
        self.patientView.setGeometry(QtCore.QRect(20, 50, 701, 251))
        self.patientView.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.patientView.setObjectName("patientView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(440, 300, 151, 51))
        self.label.setStyleSheet("font: 24pt \"Avenir\";")
        self.label.setObjectName("label")
        self.patientIDBox = QtWidgets.QLineEdit(self.centralwidget)
        self.patientIDBox.setGeometry(QtCore.QRect(370, 355, 113, 21))
        self.patientIDBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.patientIDBox.setObjectName("patientIDBox")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 350, 71, 31))
        self.label_2.setObjectName("label_2")
        self.patientAddressBox = QtWidgets.QLineEdit(self.centralwidget)
        self.patientAddressBox.setGeometry(QtCore.QRect(370, 410, 113, 21))
        self.patientAddressBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.patientAddressBox.setText("")
        self.patientAddressBox.setObjectName("patientAddressBox")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(300, 390, 51, 51))
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(500, 340, 71, 31))
        self.label_4.setObjectName("label_4")
        self.birthMonthBox = QtWidgets.QSpinBox(self.centralwidget)
        self.birthMonthBox.setGeometry(QtCore.QRect(510, 370, 48, 24))
        self.birthMonthBox.setMinimum(1)
        self.birthMonthBox.setMaximum(12)
        self.birthMonthBox.setObjectName("birthMonthBox")
        self.birthDayBox = QtWidgets.QSpinBox(self.centralwidget)
        self.birthDayBox.setGeometry(QtCore.QRect(590, 370, 48, 24))
        self.birthDayBox.setMinimum(1)
        self.birthDayBox.setMaximum(31)
        self.birthDayBox.setObjectName("birthDayBox")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(585, 340, 61, 31))
        self.label_5.setObjectName("label_5")
        self.birthYearBox = QtWidgets.QSpinBox(self.centralwidget)
        self.birthYearBox.setGeometry(QtCore.QRect(660, 370, 61, 24))
        self.birthYearBox.setMinimum(1900)
        self.birthYearBox.setMaximum(2010)
        self.birthYearBox.setObjectName("birthYearBox")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(660, 340, 61, 31))
        self.label_6.setObjectName("label_6")
        self.patientDialysisNameBox = QtWidgets.QLineEdit(self.centralwidget)
        self.patientDialysisNameBox.setGeometry(QtCore.QRect(370, 465, 113, 21))
        self.patientDialysisNameBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.patientDialysisNameBox.setText("")
        self.patientDialysisNameBox.setObjectName("patientDialysisNameBox")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(300, 450, 51, 51))
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.patientDialysisAddressBox = QtWidgets.QLineEdit(self.centralwidget)
        self.patientDialysisAddressBox.setGeometry(QtCore.QRect(580, 440, 113, 21))
        self.patientDialysisAddressBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.patientDialysisAddressBox.setText("")
        self.patientDialysisAddressBox.setObjectName("patientDialysisAddressBox")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(510, 430, 51, 51))
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.AddButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddButton.setGeometry(QtCore.QRect(500, 510, 113, 32))
        self.AddButton.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.AddButton.setObjectName("AddButton")
        self.clearFieldsButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearFieldsButton.setGeometry(QtCore.QRect(620, 510, 113, 32))
        self.clearFieldsButton.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.clearFieldsButton.setObjectName("clearFieldsButton")
        self.deleteSelectionButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteSelectionButton.setGeometry(QtCore.QRect(30, 320, 111, 51))
        self.deleteSelectionButton.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.deleteSelectionButton.setObjectName("deleteSelectionButton")
        self.editSelectionButton = QtWidgets.QPushButton(self.centralwidget)
        self.editSelectionButton.setGeometry(QtCore.QRect(150, 320, 111, 51))
        self.editSelectionButton.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.editSelectionButton.setObjectName("editSelectionButton")
        self.editSelectionButton.setText("Edit")
        self.backHomeButton = QtWidgets.QPushButton(self.centralwidget)
        self.backHomeButton.setGeometry(QtCore.QRect(20, -10, 141, 61))
        self.backHomeButton.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.backHomeButton.setObjectName("backHomeButton")
        self.maleCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.maleCheckBox.setGeometry(QtCore.QRect(310, 520, 87, 20))
        self.maleCheckBox.setObjectName("maleCheckBox")
        self.femaleCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.femaleCheckBox.setGeometry(QtCore.QRect(400, 520, 87, 20))
        self.femaleCheckBox.setObjectName("femaleCheckBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 748, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Add A Patient"))
        self.label_2.setText(_translate("MainWindow", "Patient\'s ID"))
        self.label_3.setText(_translate("MainWindow", "Patient\'s Address"))
        self.label_4.setText(_translate("MainWindow", "Birth Month"))
        self.label_5.setText(_translate("MainWindow", "Birth Day"))
        self.label_6.setText(_translate("MainWindow", "Birth Year"))
        self.label_7.setText(_translate("MainWindow", "Patient\'s Dialysis Name"))
        self.label_8.setText(_translate("MainWindow", "Patient\'s Dialysis Address"))
        self.AddButton.setText(_translate("MainWindow", "Add"))
        self.clearFieldsButton.setText(_translate("MainWindow", "Clear"))
        self.deleteSelectionButton.setText(_translate("MainWindow", "Delete"))
        self.backHomeButton.setText(_translate("MainWindow", "Back To Naratives"))
        self.maleCheckBox.setText(_translate("MainWindow", "Male"))
        self.femaleCheckBox.setText(_translate("MainWindow", "Female"))
